package com.biscuit.crm.workbench.mapper;

import com.biscuit.crm.workbench.entity.Activity;
import com.biscuit.crm.workbench.entity.ClueRemark;
import com.biscuit.crm.workbench.entity.ContactsRemark;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ContactsRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_contacts_remark
     *
     * @mbggenerated Mon Sep 05 18:55:47 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_contacts_remark
     *
     * @mbggenerated Mon Sep 05 18:55:47 CST 2022
     */
    int insert(ContactsRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_contacts_remark
     *
     * @mbggenerated Mon Sep 05 18:55:47 CST 2022
     */
    int insertSelective(ContactsRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_contacts_remark
     *
     * @mbggenerated Mon Sep 05 18:55:47 CST 2022
     */
    ContactsRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_contacts_remark
     *
     * @mbggenerated Mon Sep 05 18:55:47 CST 2022
     */
    int updateByPrimaryKeySelective(ContactsRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_contacts_remark
     *
     * @mbggenerated Mon Sep 05 18:55:47 CST 2022
     */
    int updateByPrimaryKey(ContactsRemark record);

    /**
     * 保存多条联系人备注信息
     * @param contactsRemarkList
     * @return
     */
    int saveManyContactsRemark(@Param("contactsRemarkList")List<ContactsRemark> contactsRemarkList);
}